### ISSUE TITLE
Feature request - skip PR checks

### ISSUE THREAD

**Issue by GMartinez-Sisti** [rnorth/gh-combine-prs#5]
Hi! Found this tool on the https://github.com/dependabot/dependabot-core/issues/1190 thread and it looks great.

Unfortunatelly we can't use it right away, our dependabot PRs related to tools that require authentication (e.g. terraform) will fail to pass checks and we have to retry the pipeline manually, this is because repository secrets/tokens are not available for dependabot. This a nuissance that we have accepted due to security concerns. This also means that we are not able to reach the PR creation due to the checks implemented here:

- https://github.com/rnorth/gh-combine-prs/blob/main/gh-combine-prs#L100-L103

I can send a PR with a new parameter to skip checks if you like. Just asking before submitting.

Regards

**Comment by GMartinez-Sisti** [comment]
I went ahead and forked the repo. Please let me know if you want to merge this.

https://github.com/GMartinez-Sisti/gh-combine-prs/commit/7da1f456146993217d2b7298228dccd77e177893

**Comment by rnorth** [comment]
Hi @GMartinez-Sisti thanks for the feedback and this change. Yes, if you wouldn't mind raising a PR I'd be happy to accept it!

**Comment by GMartinez-Sisti** [comment]
Thanks @rnorth :) PR created, let me know if something needs to be changed!
